#!/usr/bin/env python
# -*- coding: iso-8859-15 -*-
# generated by wxGlade 0.6.2 on Fri Aug 29 09:24:23 2008

import wx
from random_dice_roller import multiDie


# begin wxGlade: extracode
# end wxGlade

class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.panel_1 = wx.Panel(self, -1)
        self.label_1 = wx.StaticText(self.panel_1, -1, "Dice Roll Simulator")
        self.text_ctrl_1 = wx.TextCtrl(self.panel_1, -1, "")
        self.button_1 = wx.Button(self.panel_1, -1, "1d6")
        self.button_2 = wx.Button(self.panel_1, -1, "1d10")
        self.button_3 = wx.Button(self.panel_1, -1, "2d6")
        self.button_4 = wx.Button(self.panel_1, -1, "2d10")
        self.button_5 = wx.Button(self.panel_1, -1, "3d6")
        self.button_6 = wx.Button(self.panel_1, -1, "d100")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.pressed1d6, self.button_1)

    # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("frame_1")

    # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_1 = wx.GridSizer(4, 2, 0, 0)
        grid_sizer_1.Add(self.label_1, 0, 0, 0)
        grid_sizer_1.Add(self.text_ctrl_1, 0, 0, 0)
        grid_sizer_1.Add(self.button_1, 0, 0, 0)
        grid_sizer_1.Add(self.button_2, 0, 0, 0)
        grid_sizer_1.Add(self.button_3, 0, 0, 0)
        grid_sizer_1.Add(self.button_4, 0, 0, 0)
        grid_sizer_1.Add(self.button_5, 0, 0, 0)
        grid_sizer_1.Add(self.button_6, 0, 0, 0)
        self.panel_1.SetSizer(grid_sizer_1)
        sizer_1.Add(self.panel_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()

    # end wxGlade

    def pressed1d6(self, event):
        """Roll one 6-sided die."""

        self.text_ctrl_1.SetValue("")  # clears any value in text box
        val = str(multiDie(1, 1))
        self.text_ctrl_1.SetValue(val)


# end of class MyFrame

if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = MyFrame(None, -1, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()